# Generated by Django 5.0.6 on 2024-05-10 22:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Categories",
            fields=[
                ("category_id", models.BigAutoField(primary_key=True, serialize=False)),
                ("name", models.TextField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name="Items",
            fields=[
                ("item_id", models.BigAutoField(primary_key=True, serialize=False)),
                ("name", models.TextField(max_length=64)),
                ("description", models.TextField(max_length=256)),
                ("quantity", models.IntegerField()),
                ("cost", models.DecimalField(decimal_places=2, max_digits=7)),
                ("updated_on", models.DateTimeField(auto_now=True)),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="api.categories",
                    ),
                ),
            ],
        ),
    ]
