# Generated by Django 5.0.6 on 2024-05-10 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Images",
            fields=[
                ("image_id", models.BigAutoField(primary_key=True, serialize=False)),
                ("uri", models.TextField(max_length=256)),
            ],
        ),
        migrations.AddField(
            model_name="items",
            name="images",
            field=models.ManyToManyField(to="api.images"),
        ),
    ]
